= Acknowledgements

I'm extremely grateful to my family, for putting up with my late nights and extended screen time while I worked on this book.

To Rod Johnson and Juergen Hoeller, thanks for inventing Spring and changing the lives of Java developers forever. To Phil Webb and Dave Syer, thanks for creating Spring Boot and breathing a breath of fresh air into the Spring Framework. Last but not least, thanks to Josh Long for first showing me Spring Boot and for being one of the most enthusiastic Spring developers I've ever met.

I'd like to thank this book's tech editors, Dennis Sharpe and Jeet Gajjar. Their real-world experience with JHipster made the code sections a lot more bulletproof.

This book's copy editor, Lawrence Nyveen, was a tremendous help in correcting my words and making this book easier to read. Thanks Laurie!

Finally, kudos to Julien Dubois and Deepu K Sasidharan for creating and improving JHipster. They've done a helluva job in turning it into a widely used and successful open-source project.
