
=== AngularJS
=== Bootstrap

Bootstrap is a CSS framework that simplifies the development of web applications. It provides a number of CSS classes
and HTML structures that allow you to develop HTML user interfaces that look good by default. Not only that, but its
latest version is responsive by default, which means it works better (or even best) on a mobile device.

===== The Grid System

Most CSS frameworks provide a grid system that allows you to position columns and cells in a respectable way. Bootstrap's
basic grid system is composed of containers, rows and columns. For example:

[source,html,linenums]
----
include::{sourcedir}/../webapp/grid-basic.html[]
----

_[screenshot]_

Bootstrap's grid can be used to align and position elements, widgets and features of your application. It's helpful
to understand a few basics want to use it effectively.

* It's based on 12 columns
* Just use 'md' and fix as needed
* It can be used to size input fields

Bootstrap 3's grid system has four tiers of classes: xs (phones), sm (tablets), md (desktops), and lg (larger desktops).
You can use nearly any combination of these classes to create more dynamic and flexible layouts. Below is an example of a
grid that's a little more advanced.

Each tier of classes scales up, meaning if you plan on setting the same widths for xs and sm, you only need to specify xs.

[source,html,linenums]
----
include::{sourcedir}/../webapp/grid-advanced.html[]
----

_[screenshot]_

You can use size indicators to specify breakpoints in the columns. Breakpoints specify where a column wraps onto the next
row. In the HTML above, 'md' is the size indicator. Boostrap supports 'xs', 'sm', 'md', 'lg' and 'xl'.

_todo: include breakpoints if it can be done in a paragraph or two_

===== Forms
When you add Bootstrap's CSS to your web application, chances are it'll start to look better quickly. Typography, margins,
and padding will look better by default. However, your forms might look funny. This is because Bootstrap requires a few
classes on your form elements to make them look good. Below is an example of a form element.

[source,html,linenums]
----
include::{sourcedir}/../webapp/basicelement.html[]
----

_[screenshot]_

If you'd like to indicate this form element is not valid, you'll need to modify the above HTML to display validation warnings.

[source,html,linenums]
----
include::{sourcedir}/../webapp/basicelement-withvalidation.html[]
----

_[screenshot]_

===== Components (alerts, dropdowns, navbars)

_you might want to look at http://raibledesigns.com/repository/presentations/bootstrap3/#1, it's really quite good!_

===== Icons


====== Font Awesome

=== i18n
=== Sass
=== Grunt vs. Gulp.js
=== WebSockets
=== BrowserSync

http://www.browsersync.io/[BrowserSync] is one of those tools that make you wonder how you ever lived without them. It's a program that
keeps your assets in sync with your browser. It's also capable of syncing browsers, so you can scroll in
Safari and watch a Chrome window scroll, along with a Safari window running in iOS Simulator. When you save
files, it updates your browser windows, saving you an incredible amount of time. As its website says:
"It's wicked-fast and totally free".

BrowserSync is free to run and reuse, as guaranteed by its open source Apache 2.0 License. It contains a number of slick features:

* Interaction sync: Your scroll, click, refresh and form actions are mirrored between browsers while you test.
* File sync: Browsers are automatically updated as you change HTML, CSS, images and other project files.
* URL history: Records your test URLs so you can push them back out to all devices with a single click.
* Remote inspector: Remotely tweak and debug web pages that are running on connected devices.
* Browser support: Instantly sync between your desktop, tablet and phone. Perfect for coding responsive designs.
* Build-tool compatible: Easily integrated with task runners like Grunt and Gulp, or included in other Node projects.
* Install and run anywhere: Built on Node.js to support Windows, MacOS and Linux. Setup in less than 5 minutes.

To integrate BrowserSync in your project, you need a `package.json` and `Gruntfile.js`. Your `package.json` file only needs
to contain a few things, weighing in at a slim 15 lines of JSON.

[source,javascript,linenums]
----
include::{sourcedir}/../../../package.json[]
----

The `Gruntfile.js` utilizes the tools specified in `package.json` to enable BrowserSync and create a magical web development
experience.

[source,javascript,linenums]
----
include::{sourcedir}/../../../Gruntfile.browsersync.js[]
----

After you've created these files, you'll need to install https://nodejs.org/[Node] and its package manager (NPM). Then you
should be able to run the following command to install BrowserSync and Grunt. You will only need to run this command when
dependencies change in `package.json`.
----
npm install
----
You may have to install http://gruntjs.com/[Grunt] as well. Install the grunt command-line tool globally with:
----
npm install -g grunt-cli
----
Then run the following command to create a blissful development experience where your browser auto-refreshes when files change
on your hard drive.
----
grunt serve
----
For an audio visual introduction to BrowserSync, check out the introduction video on its http://www.browsersync.io/[homepage].

JHipster integrates BrowserSync for you, using JavaScript similar that looks very similar to what you see above. Integrating
BrowserSync into your project is highly recommended. It's also useful for determining if your web application can handle a
page reload without losing the current user's state.
