== Preface

Over the last few years, I've consulted at several companies that used Spring and Java to develop their backend systems. On those projects, I introduced Spring Boot to simplify development. Its external configuration feature was often admired by DevOps teams and its starter dependencies made it easy to develop SOAP and REST APIs.

I've used AngularJS for several years as well. The first project I used Angular on was in early 2013 and I implemented in 40% of the code that jQuery would've required. I helped that company do UI overhaul project where we integrated Bootstrap and made their UI into a modern one. I was very impressed with both Angular and Bootstrap and have used them ever since. In 2014, I used Ionic on a project to implement an HTML5 UI in a native iOS application. Angular, Bootstrap and Spring Boot were used on that project and worked very well for us.

When I heard about JHipster, I was motivated to use it right away. It combined my most-often-used frameworks into an easy-to-use package. For the first several months I knew about JHipster, I used it as a learning tool - generating projects and digging into files to see how features were coded. The JHipster project is a goldmine of information and learnings from several years of its developer's experience.

I wanted to write this book because I knew all the tools in JHipster really well. I wanted to spread the knowledge of this wonderful project. I wanted Java developers to see that they can be hip again by leveraging Angular and Bootstrap. I wanted to show them how JavaScript web development isn't scary, it's just another powerful platform that can improve your web development skills.

=== What is in an InfoQ mini-book?

InfoQ mini-books are designed to be concise, intending to serve technical architects looking to get a firm conceptual understanding of a new technology or technique in a quick yet in-depth fashion. You can think of these books as covering a topic strategically or essentially. After reading a mini-book, the reader should have a fundamental understanding of a technology, including when and where to apply it, how it relates to other technologies, and an overall feeling that they have assimilated the combined knowledge of other professionals who have already figured out what this technology is about. The reader will then be able to make intelligent decisions about the technology once their projects require it, and can delve into sources of more detailed information (such as larger books, or tutorials) at that time.

=== Who this book is for

This book is aimed specifically at web developers who want a rapid introduction to AngularJS, Bootstrap and Spring Boot by learning JHipster.

=== What you need for this book

To try code samples in this book, you will need a computer running an up-to-date operating system (Windows, Linux, or Mac OS X). Node and Java will need to be installed. The book code was tested against Node v0.12 and JDK 8, but newer versions should also work.

=== Conventions

We use a number of typographical conventions within this book that distinguish between different kinds of information.

Code in the text, including commands, variables, file names, CSS class names, and property names are shown as follows:

"Spring Boot uses a `public static void main` entry-point that launches an embedded web server for you."

A block of code is set out as follows. It may be colored, depending on which format you're reading this book in.

[source,html]
.src/main/webapp/form.html
----
<form ng-submit="search()">
    <input type="search" name="search" ng-model="term">
    <button>Search</button>
</form>
----

[source,java]
.src/main/java/demo/DemoApplication.java
----
@RestController
class BlogController {

    @RequestMapping("/blogs")
    Collection<Blog> list() {
        return repository.findAll();
    }

    @Autowired
    BlogRepository repository;
}
----

When we want to draw your attention to a particular part of the code it's called out with numbers.

[source,javascript,linenums]
----
.controller('SearchController', function ($scope, SearchService) { <1>
    $scope.search = function () { <2>
        console.log("Search term is: " + $scope.term); <3>
        SearchService.query($scope.term).then(function (response) {
            $scope.searchResults = response.data;
        });
    };
})
----
<1> To inject SearchService into SearchController, simply add it as a parameter to the controller's argument list.
<2> `$scope.search()` is a function that's called from HTML `<form>`, wired up using the `ng-submit` directive.
<3> `$scope.term` is a variable that's wired to `<input>` using the `ng-model` directive.

TIP: Tips are shown using callouts like this.

WARNING: Warnings are shown using callouts like this.

.Sidebar
****
Additional information about some topics are is displayed using a sidebar like this.
****

Finally, the text shows what a quote looks like.

"In the end, it's not the years in your life that count. It's the life in your years."
-- Abraham Lincoln

=== Reader feedback

We always welcome feedback from our readers. Let us know what you think about this book — what you liked or disliked. Reader feedback helps us develop titles that you get the most out of.

To send us feedback email us at feedback@infoq.com, send a tweet to https://twitter.com/jhipster_book[@jhipster_book] or post a question on Stack Overflow with the http://stackoverflow.com/tags/jhipster-book/info[jhipster-mini-book] tag.

If you have a topic that you have expertise in and you are interested in either writing or contributing to a book, please take a look at our minibook guidelines on http://www.infoq.com/minibook-guidelines.
