= Preface

Over the last few years, I've consulted at several companies that used Spring and Java to develop their back-end systems. On those projects, I introduced Spring Boot to simplify development. DevOps teams often admired its external configuration and its starter dependencies made it easy to develop SOAP and REST APIs.

I used AngularJS for several years as well. For the first project I used AngularJS on, in early 2013, I implemented in 40% of the code that jQuery would've required. I helped that company modernize its UI in a project for which we integrated Bootstrap. I was very impressed with both Angular and Bootstrap and have used them ever since. In 2014, I used Ionic on a project to implement a HTML5 UI in a native iOS application. We used Angular, Bootstrap, and Spring Boot in that project and they worked very well for us.

When I heard about JHipster, I was motivated to use it right away. It combined my most-often-used frameworks into an easy-to-use package. For the first several months I knew about JHipster, I used it as a learning tool — generating projects and digging into files to see how it coded features. The JHipster project is a goldmine of information and lessons from several years of developer experience.

I wanted to write this book because I knew all the tools in JHipster really well. I wanted to further the knowledge of this wonderful project. I wanted Java developers to see that they can be hip again by leveraging Angular and Bootstrap. I wanted to show them how JavaScript web development isn't scary, it's just another powerful platform that can improve your web-development skills.

== What is in an InfoQ mini-book?

InfoQ mini-books are designed to be concise, intending to serve technical architects looking to get a firm conceptual understanding of a new technology or technique in a quick yet in-depth fashion. You can think of these books as covering a topic strategically or essentially. After reading a mini-book, the reader should have a fundamental understanding of a technology, including when and where to apply it, how it relates to other technologies, and an overall feeling that they have assimilated the combined knowledge of other professionals who have already figured out what this technology is about. The reader will then be able to make intelligent decisions about the technology once their projects require it, and can delve into sources of more detailed information (such as larger books or tutorials) at that time.

== Who this book is for

This book is aimed specifically at web developers who want a rapid introduction to Angular, Bootstrap, and Spring Boot by learning JHipster.

== What you need for this book

To try code samples in this book, you will need a computer running an up-to-date operating system (Windows, Linux, or Mac OS X/MacOS). You will need Node.js and Java installed. The book code was tested against Node.js 8 and JDK 8, but newer versions should also work.

== Conventions

We use a number of typographical conventions within this book that distinguish between different kinds of information.

Code in the text, including commands, variables, file names, CSS class names, and property names are shown as follows:

[example]
Spring Boot uses a `public static void main` entry-point that launches an embedded web server for you.

A block of code is set out as follows. It may be colored, depending on the format in which you're reading this book.

[source,html]
.src/app/search/search.component.html
----
<form>
  <input type="search" name="query" [(ngModel)]="query" (keyup.enter)="search()">
  <button type="button" (click)="search()">Search</button>
</form>
----

[source,java]
.src/main/java/demo/DemoApplication.java
----
@RestController
class BlogController {
    private final BlogRepository repository;

    // Yippee! No annotations needed for constructor injection in Spring 4.3+.
    public BlogController(BlogRepository repository) {
        this.repository = repository;
    }

    @RequestMapping("/blogs")
    Collection<Blog> list() {
        return repository.findAll();
    }
}
----

When we want to draw your attention to certain lines of code, those lines are annotated using numbers accompanied by brief descriptions.

[source,javascript]
----
export class SearchComponent {
  constructor(private searchService: SearchService) {} <1>

  search(): void { <2>
    this.searchService.search(this.query).subscribe( <3>
      data => { this.searchResults = data; },
      error => console.log(error)
    );
  }
}
----
<1> To inject `SearchService` into `SearchComponent`, add it as a parameter to the controller's argument list.
<2> `search()` is a method that's called from the HTML's `<button>`, wired up using the `(click)` event handler.
<3> `this.query` is a variable that's wired to `<input>` using two-way binding with `[(ngModel)]="query"`.


TIP: Tips are shown using callouts like this.

WARNING: Warnings are shown using callouts like this.

.Sidebar
****
Additional information about a certain topic may be displayed using a sidebar like this one.
****

Finally, this text shows what a quote looks like.

"In the end, it's not the years in your life that count. It's the life in your years."
-- Abraham Lincoln

== Reader feedback

We always welcome feedback from our readers. Let us know what you thought about this book — what you liked or disliked. Reader feedback helps us develop titles that deliver the most value to you.

To send us feedback, e-mail us at feedback@infoq.com, send a tweet to https://twitter.com/jhipster_book[@jhipster_book], or post a question on Stack Overflow using the "`jhipster`" tag.

If there is a topic in which you have expertise and you are interested in either writing or contributing to a book, please take a look at our mini-book guidelines at http://www.infoq.com/minibook-guidelines.
