== Preface

Over the last few years, I've consulted at several companies that used Spring and Java to develop their backend systems. On those projects, I introduced Spring Boot to simplify development. Its external configuration feature was often admired by DevOps teams and its starter dependencies made it easy to develop SOAP and REST APIs.

I've used AngularJS for several years as well. The first project I used Angular on was in early 2013 and I implemented in 40% of the code that jQuery would've required. I helped that company do UI overhaul project where we integrated Bootstrap and made their UI into a modern one. I was very impressed with both Angular and Bootstrap and have used them ever since. In 2014, I used Ionic on a project to implement an HTML5 UI in a native iOS application. Angular, Bootstrap and Spring Boot were used on that project and worked very well for us.

When I heard about JHipster, I was motivated to use it right away. It combined my most-often-used frameworks into an easy-to-use package. For the first several months I knew about JHipster, I used it as a learning tool - generating projects and digging into files to see how features were coded. The JHipster project is a goldmine of information and learnings from several years of its developer's experience.

I wanted to write this book because I knew all the tools in JHipster really well. I wanted to spread the knowledge of this wonderful project. I wanted Java developers to see that they can be hip again by leveraging Angular and Bootstrap. I wanted to show them how JavaScript web development isn't scary, it's just another powerful platform that can improve your web development skills.

=== What is in an InfoQ mini-book?

InfoQ mini-books are designed to be concise, intending to serve technical architects looking to get a firm conceptual understanding of a new technology or technique in a quick yet in-depth fashion. You can think of these books as covering a topic strategically or essentially. After reading a mini-book, the reader should have a fundamental understanding of a technology, including when and where to apply it, how it relates to other technologies, and an overall feeling that they have assimilated the combined knowledge of other professionals who have already figured out what this technology is about. The reader will then be able to make intelligent decisions about the technology once their projects require it, and can delve into sources of more detailed information (such as larger books, or tutorials) at that time.

=== Who this book is for

This book is aimed specifically at web developers who want a rapid introduction to AngularJS, Bootstrap and Spring Boot by learning JHipster.

=== What you need for this book

To try code samples in this book, you will need a computer running an up-to-date operating system (Windows, Linux, or Mac OS X). Node and Java will need to be installed. The book code was tested against Node v0.12 and JDK 8, but newer versions should also work.

=== Conventions

// MR: Not sure if these should be defined the same as other books since the styles might be provided by Asciidoctor.

=== Reader feedback

We always welcome feedback from our readers. Let us know what you think about this book — what you liked or disliked. Reader feedback helps us develop titles that you get the most out of.

To send us feedback email us at feedback@infoq.com or send a tweet to https://twitter.com/jhipster_book[@jhipster_book].

If you have a topic that you have expertise in and you are interested in either writing or contributing to a book, please take a look at our minibook guidelines on http://www.infoq.com/minibook-guidelines.
