version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      asciidoctor:
        patterns:
          - "org.asciidoctor.jvm.*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
