= The JHipster Mini-Book

image:https://github.com/mraible/jhipster-book/actions/workflows/ci.yml/badge.svg[link=https://github.com/mraible/jhipster-book/actions/workflows/ci.yml]

This is an awesome book. It's written in AsciiDoc and compiles to HTML, PDF, EPUB, and MOBI using the http://asciidoctor.org/docs/asciidoctor-gradle-plugin/[Asciidoctor Gradle plugin].

== Installing

 $ npm run setup

== Building

To convert this book to HTML and EPUB, run the following command:

 $ npm run build

* Open build/asciidoc/html5/index.html in your browser to see the generated HTML file.
* Open build/asciidoc/pdf-prepress/index.pdf to see the 6x9" printable PDF file.
* Open build/asciidoc/pdf-screen/index.pdf to see the downloadable 8.5x11" PDF file.
* Open build/asciidoc/epub3/index.epub in iBooks to see the generated EPUB file.

== Sweet Authoring Experience

If you'd like a very pleasant authoring experience, the project provides build files that make it possible. First of all, you'll need to run `gradlew` once. After running it once, you can run `./gradlew watch` to watch for any changes and recompile files as you save them.

To have a similar awesome experience (watch and auto-reload) in your browser, install https://nodejs.org/[Node.js] on your machine.

After installing Node, you can run the following command to install development tools (like http://www.browsersync.io/[Browsersync]). You will only need to run this command when dependencies change in `package.json`.

----
npm install
----

This project use http://gulpjs.com/[Gulp] as the client-code build system. You can install the `gulp` command-line tool globally with:

----
npm install -g gulp-cli
----

Now you can run the following `gulp` command to create a blissful development experience where your browser auto-refreshes when files change on your hard drive.

----
gulp
----
